analyzer:
  errors:
    avoid_print: ignore
    prefer_typing_uninitialized_variables: ignore
    unnecessary_this: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # 🔹 Existing project rules
    # avoid_print: false
    # prefer_single_quotes: true

    # 🔹 Force const usage rules
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true
