// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGVrph1btQR0ZCudt7c1Y1MqNDtkxnGIg',
    appId: '1:106443104504:web:b4200203b24ad6cd9cdb0d',
    messagingSenderId: '106443104504',
    projectId: 'wavee-dcf27',
    authDomain: 'wavee-dcf27.firebaseapp.com',
    storageBucket: 'wavee-dcf27.firebasestorage.app',
    measurementId: 'G-QY0TK3233S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmz0t3_EFyHxuu9YKIakEjTq_eqKS2PdQ',
    appId: '1:106443104504:android:dc0b8069e2c099d09cdb0d',
    messagingSenderId: '106443104504',
    projectId: 'wavee-dcf27',
    storageBucket: 'wavee-dcf27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBui3Z0r5cX9ovOiqVmJyLPANMncyxajO4',
    appId: '1:106443104504:ios:c85bbfe6d9d612949cdb0d',
    messagingSenderId: '106443104504',
    projectId: 'wavee-dcf27',
    storageBucket: 'wavee-dcf27.firebasestorage.app',
    iosBundleId: 'com.wavee.community',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBui3Z0r5cX9ovOiqVmJyLPANMncyxajO4',
    appId: '1:106443104504:ios:c85bbfe6d9d612949cdb0d',
    messagingSenderId: '106443104504',
    projectId: 'wavee-dcf27',
    storageBucket: 'wavee-dcf27.firebasestorage.app',
    iosBundleId: 'com.wavee.community',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGVrph1btQR0ZCudt7c1Y1MqNDtkxnGIg',
    appId: '1:106443104504:web:0cbfd7968d8c681f9cdb0d',
    messagingSenderId: '106443104504',
    projectId: 'wavee-dcf27',
    authDomain: 'wavee-dcf27.firebaseapp.com',
    storageBucket: 'wavee-dcf27.firebasestorage.app',
    measurementId: 'G-ZLTLN723SJ',
  );
}
