// ignore_for_file: non_constant_identifier_names, constant_identifier_names

import 'package:intl/intl.dart';
import 'package:wavee/Screen/Authcation/Model/DeleteAccountModel.dart';
import 'package:wavee/Screen/Authcation/Model/forgotPasswordModel.dart';
import 'package:wavee/Screen/Authcation/Model/login_model.dart';
import 'package:wavee/Screen/Booking/Model/amenities_book_status_model.dart';
import 'package:wavee/Screen/Buy%20Product/place_order_model.dart';
import 'package:wavee/Screen/Chatscreen/Model/Chatstorymodal.dart';
import 'package:wavee/Screen/Community%20Screen/Community%20Screen/Model/BusnessViewModal.dart';
import 'package:wavee/Screen/Manintenance/Model/maintenance_detail_model.dart';
import 'package:wavee/Screen/homePage/Model/parcel_show_count.dart';
import 'package:wavee/Screen/homePage/Model/visitor_show_count_model.dart';
import 'package:wavee/Screen/upcomingRequest/Model/get_my_new_request.dart';
import 'package:wavee/Screen/viewProfile/Model/profile_model.dart';

import '../Screen/Add to Cart/model/add_to_cart_model.dart';
import '../Screen/Booking/Model/AllAmenitiesModel.dart';
import '../Screen/Booking/Model/booking_model.dart';
import '../Screen/Booking/Model/event_booking_modal.dart';
import '../Screen/Booking/Model/event_detail_model.dart';
import '../Screen/Booking/Model/rejectbooking.dart';
import '../Screen/Booking/Model/service_booking_model.dart';
import '../Screen/Category/Modal/category_detail_modal.dart';
import '../Screen/Chatscreen/Model/chat_screen_model.dart';
import '../Screen/Community Detail Page/Model/SearchProductModel.dart';
import '../Screen/Community Detail Page/Model/category_modal.dart';
import '../Screen/Community Screen/Community Screen/Model/BusinessSearchModal.dart';
import '../Screen/Community Screen/Community Screen/Model/CategoriesModel.dart';
import '../Screen/Community Screen/Community Screen/Model/DwellTimeModel.dart';
import '../Screen/Community Screen/Community Screen/Model/GetLikeModal.dart';
import '../Screen/Community Screen/Community Screen/Model/GetVisitedModal.dart';
import '../Screen/Community Screen/Community Screen/Model/OfferPromoAsViewedModel.dart';
import '../Screen/Community Screen/Community Screen/Model/PostAsViewedModel.dart';
import '../Screen/Community Screen/Community Screen/Model/RequestModal.dart';
import '../Screen/Community Screen/Community Screen/Model/StroyModel.dart';
import '../Screen/Community Screen/Community Screen/Model/ViewCategoriesModel.dart';
import '../Screen/Community Screen/Community Screen/Model/businesslikemodel.dart';
import '../Screen/Community Screen/Community Screen/Model/businessprofilemodel.dart';
import '../Screen/Community Screen/Community Screen/Model/postlikemodel.dart';
import '../Screen/Event/Model/eventDetailModal.dart';
import '../Screen/Event/Model/event_model.dart';
import '../Screen/Event/Model/send_event_model.dart';
import '../Screen/Manintenance/Model/maintenance_modal.dart';
import '../Screen/NotiFicationPage/Model/Notification_Model.dart';
import '../Screen/NotiFicationPage/Model/ReadNotificationModel.dart';
import '../Screen/Parcel/Model/parcel_model.dart';
import '../Screen/Visitor/Model/latest_visitor_modal/latest_visitor_modal.dart';
import '../Screen/homePage/Model/chat_show_count_modal.dart';
import '../Screen/homePage/Model/message_board_modal.dart';
import '../Screen/messageBoard/Model/AddGroupMemberModel.dart';
import '../Screen/messageBoard/Model/Add_Post_Model.dart';
import '../Screen/messageBoard/Model/ChatUserListModel.dart';
import '../Screen/messageBoard/Model/CreateFriendModel.dart';
import '../Screen/messageBoard/Model/CreateGroupModel.dart';
import '../Screen/messageBoard/Model/DeleteGroupModel.dart';
import '../Screen/messageBoard/Model/GetFriendListModel.dart';
import '../Screen/messageBoard/Model/GetGroupListModel.dart';
import '../Screen/messageBoard/Model/GetMsgModel.dart';
import '../Screen/messageBoard/Model/GetPostCommentsModel.dart';
import '../Screen/messageBoard/Model/GetRequestModel.dart';
import '../Screen/messageBoard/Model/GroupProfileModel.dart';
import '../Screen/messageBoard/Model/Localpost_comments_Model.dart';
import '../Screen/messageBoard/Model/Localpost_model.dart';
import '../Screen/messageBoard/Model/PostLikeModel.dart';
import '../Screen/messageBoard/Model/RemoveGroupMemberModel.dart';
import '../Screen/messageBoard/Model/ResidentAppUserprofileModel.dart';
import '../Screen/messageBoard/Model/SendMsgModel.dart';
import '../Screen/messageBoard/Model/SendPostCommentsModel.dart';
import '../Screen/messageScreen/Model/OrderSendMessageModel.dart';
import '../Screen/messageScreen/Model/RemoveFriendModel.dart';
import '../Screen/messageScreen/Model/SendMessageModel.dart';
import '../Screen/messageScreen/Model/UserPersonalInfoModel.dart';
import '../Screen/messageScreen/Model/messagescreen_model.dart';
import '../Screen/openAiChatbot/modal/chat_bot_data_modal.dart';
import '../Screen/openAiChatbot/modal/send_data_model.dart';
import '../Screen/orderScreen/Model/order_detail_model.dart';
import '../Screen/orderScreen/Model/order_screen_model.dart';
import '../Screen/orderScreen/Model/service_order_model.dart';
import '../Screen/orderScreen/Model/service_view_model.dart';
import '../Screen/productDetailPage/model/all_review_model.dart';
import '../Screen/productDetailPage/model/product_model.dart';
import '../Screen/serviceDetailPage/Model/ServiceDetailsModel.dart';
import '../Screen/upcomingRequest/Model/OnGoing_Freind_Request_Model.dart';
import '../Screen/upcomingRequest/Model/my_request_model.dart';

const String baseUrl = "https://portal.wavee.ai/api";
const String jsonString = "assets/google_pay.json";

String formatDateTime(String? createdAt) {
  if (createdAt == null || createdAt.isEmpty) return "N/A";
  DateTime parsedDate = DateTime.parse(createdAt);
  return "${DateFormat('dd MMM yyyy').format(parsedDate)}, ${DateFormat('hh:mm a').format(parsedDate)}";
}

class AppConstants {
  static String BASEURL = "https://portal.wavee.ai/api/";
  // static String BASEURL = "https://staging-portal.wavee.ai/api/";

  static const String path = "assets/Svg/";
  static const String manrope1 = "AlbertSans-SemiBold";
  // static const String manropeBold = "AlbertSans-Bold";
  static const String manropeBold = "AlbertSans-SemiBold";
  static const String manrope = "AlbertSans";
  static const String AlbertSansLight = "AlbertSans-Light";

  static const String homeScreen = "assets/images/homescreen_map.png";
  static const String home = "${path}home.svg";
  static const String cart = "${path}cart.svg";
  static const String chat1 = "${path}chat1.svg";
  static const String community = "${path}community.svg";
  static const String chat = "${path}chat.svg";
  static const String parcel = "${path}parcel.svg";
  static const String visitor = "${path}visitor.svg";
  static const String amenities = "${path}amenities.svg";
  static const String building = "${path}building.svg";
  static const String booking = "${path}booking.svg";
  static const String maintance = "${path}maintance.svg";
  static const String events = "${path}events.svg";
  static const String myOrder = "${path}myorder.svg";
  static const String serviceBooking = "${path}servicebooking.svg";
  static const String shopping = "${path}shopping.svg";
  static const String profile = "${path}profile.svg";
  static const String settings = "${path}settings.svg";
  static const String Privacy = "${path}Privacy1.svg";
  static const String terms = "${path}terms.svg";
  static const String messageBoard = "${path}messageboard.svg";
  static const String eventBooking = "${path}eventbookin.svg";
  static const String waveePet = "${path}waveePet.svg";
}

LoginModel? loginModel;
Forgotpasswordmodel? forgotpasswordmodel;
DeleteAccountModel? deleteAccountModel;
ParcelViewModal? parcelViewModal;
BusinessProfileModel? businessprofileModel;
BusnessViewModal? busnessviewmodal;
ProfileModel? profileModel;
ParcelShowCountModel? parcelShowCountModel;
VisitorShowCountModel? visitorShowCountModel;
BussinessLikeModel? bussinesslikemodel;
LatestVisitorModal? latestVisitorModal;
ChatShowCountModal? chatShowCountModal;
MessageBoardModal? messageBoardModal;
ChatModel? chatModel;
MessageModel? messageModel;
BusnessSearchModal? busnesssearchModal;
GetLikeModal? getlikeModal;
GetVisitedModal? getvisitedModal;
SendMessageModel? sendMessageModel;
RequestModal? requestmodal;
EventlistModel? eventlistModel;
NotificationModell? notificationmodel;
NotificationReadModel? notificationreadModel;
EventlistModel? event_list_Model;
SendeventModel? sendeventModel;
CategoriesModel? categoriesModel;
ViewCategoriesModel? viewcategoriesmodel;
PostLikeModel? postlikemodel;
DwellTimeModel? dwelltimemodel;
PostAsViewedModel? postasviewedmodel;
OfferPromoAsViewedModel? offerpromoAsviewedmodel;
ChatUserListModel? chatuserlistmodel;
GetGroupListModel? getgrouplistmodel;
CreateGroupModel? creategroupmodel;
GroupProfileModel? groupprofileModel;
RemoveGroupMemberModel? removegroupMemberModel;
AddGroupMemberModel? addgroupMemberModel;
DeleteGroupModel? deletegroupModel;
RemoveFriendModel? removefriendModel;
UserPersonalInfoModel? userpersonalInfoModel;
SendMsgModel? sendmsgModel;
GetMsgModel? getmsgModel;
CreateFriendModel? createfriendModel;
GetFriendListModel? getfriendListModel;
ChatbotDataModal? chatbotDataModal;
SendChatModal? sendChatModal;
AmenitiesModel? amenitiesModel;
AmenitiesModel? aneminitiesDataModel;
AllAmenitiesModel? allAmenitiesModel;
RejectBookingModel? rejectBookingModel;
BookAmenitiesStatusModel? bookAmenitiesStatusModel;
MaintenanceModel? maintenanceModel;
EventBookingModal? eventBookingModal;
GetPostCommentsModel? getpostCommentsModel;
MessageboardpostLikeModel? messageboardpostlikeModel;
SendPostCommentsModel? sendpostCommentsModel;
MaintenanceDetailModel? maintenanceDetailModel;
EventDetailModel? eventDetailModel;
ProductViewModel? productViewModel;
ShowAllReviewModel? showAllReviewModel;
CartDetailsModel? cartDetailsModel;
CartDetailsModel? checkoutTotal;
MyOrderModel? myOrderModel;
OrderDetailModel? orderDetailModel;
PlaceOrderModel? placeOrderModel;
StroyModel? stroymodel;
GetRequestModel? getrequestModel;
MyRequestModel? myRequestModel;
OnGoingFreindRequestModel? onGoingFreindRequestModel;
MyGroupRequestModel? myGroupRequestModel;
ResidentAppUserprofileModel? residentappuserprofileModel;
ServiceDetailsModel? servicedetailsmodel;
ServiceOrderDetail? serviceOrderDetail;
ServiceViewModel? serviceViewModel;
ServiceBookingModel? serviceBookingModel;
Localpost_model? localpost_model;
Localpost_comments_Model? localpostCommentsModel;
Add_Post_Model? add_Post_Model;
CategoryModal? categoryModal;
CategoryDetailModal? categoryDetailModal;
OrdersendMessageModel? ordersendmessagemodel;
SearchProductModel? searchproductmodel;
ChatStoryModal? chatStories;
EventDetailModal? eventDetailModal;
