import 'package:wavee/Screen/Authcation/model/login_model.dart';
import 'package:wavee/Screen/Booking/Model/amenities_book_status_model.dart';
import 'package:wavee/Screen/Buy%20Product/place_order_model.dart';
import 'package:wavee/Screen/Community%20Screen/Community%20Screen/Model/BusnessViewModal.dart';
import 'package:wavee/Screen/HomeNewPage/Model/parcel_show_count.dart';
import 'package:wavee/Screen/HomeNewPage/Model/visitor_show_count_model.dart';
import 'package:wavee/Screen/Manintenance/Model/maintenance_detail_model.dart';

import 'package:wavee/Screen/UpcomingRequest/Model/get_my_new_request.dart';
import 'package:wavee/Screen/ViewProfile/Model/profile_model.dart';

import '../Screen/Add to Cart/model/add_to_cart_model.dart';
import '../Screen/Authcation/Model/delete_account_model.dart';
import '../Screen/Authcation/Model/forgotPasswordModel.dart';
import '../Screen/Booking/Model/AllAmenitiesModel.dart';
import '../Screen/Booking/Model/booking_model.dart';
import '../Screen/Booking/Model/event_booking_modal.dart';
import '../Screen/Booking/Model/event_detail_model.dart';
import '../Screen/Booking/Model/rejectbooking.dart';
import '../Screen/Booking/Model/service_booking_model.dart';
import '../Screen/Chatscreen/Model/chat_screen_model.dart';
import '../Screen/Community Screen/Community Screen/Model/BusinessSearchModal.dart';
import '../Screen/Community Screen/Community Screen/Model/CategoriesModel.dart';
import '../Screen/Community Screen/Community Screen/Model/DwellTimeModel.dart';
import '../Screen/Community Screen/Community Screen/Model/GetLikeModal.dart';
import '../Screen/Community Screen/Community Screen/Model/GetVisitedModal.dart';
import '../Screen/Community Screen/Community Screen/Model/OfferPromoAsViewedModel.dart';
import '../Screen/Community Screen/Community Screen/Model/PostAsViewedModel.dart';
import '../Screen/Community Screen/Community Screen/Model/RequestModal.dart';
import '../Screen/Community Screen/Community Screen/Model/StroyModel.dart';
import '../Screen/Community Screen/Community Screen/Model/ViewCategoriesModel.dart';
import '../Screen/Community Screen/Community Screen/Model/businesslikemodel.dart';
import '../Screen/Community Screen/Community Screen/Model/businessprofilemodel.dart';
import '../Screen/Community Screen/Community Screen/Model/postlikemodel.dart';
import '../Screen/Event/Model/event_model.dart';
import '../Screen/Event/Model/send_event_model.dart';
import '../Screen/HomeNewPage/Model/chat_show_count_modal.dart';
import '../Screen/HomeNewPage/Model/message_board_modal.dart';
import '../Screen/Manintenance/Model/maintenance_modal.dart';
import '../Screen/Message_board/Model/AddGroupMemberModel.dart';
import '../Screen/Message_board/Model/Add_Post_Model.dart';
import '../Screen/Message_board/Model/ChatUserListModel.dart';
import '../Screen/Message_board/Model/CreateFriendModel.dart';
import '../Screen/Message_board/Model/CreateGroupModel.dart';
import '../Screen/Message_board/Model/DeleteGroupModel.dart';
import '../Screen/Message_board/Model/GetFriendListModel.dart';
import '../Screen/Message_board/Model/GetGroupListModel.dart';
import '../Screen/Message_board/Model/GetMsgModel.dart';
import '../Screen/Message_board/Model/GetPostCommentsModel.dart';
import '../Screen/Message_board/Model/GetRequestModel.dart';
import '../Screen/Message_board/Model/GroupProfileModel.dart';
import '../Screen/Message_board/Model/Localpost_comments_Model.dart';
import '../Screen/Message_board/Model/Localpost_model.dart';
import '../Screen/Message_board/Model/PostLikeModel.dart';
import '../Screen/Message_board/Model/RemoveGroupMemberModel.dart';
import '../Screen/Message_board/Model/ResidentAppUserprofileModel.dart';
import '../Screen/Message_board/Model/SendMsgModel.dart';
import '../Screen/Message_board/Model/SendPostCommentsModel.dart';
import '../Screen/Message_screen/Model/RemoveFriendModel.dart';
import '../Screen/Message_screen/Model/SendMessageModel.dart';
import '../Screen/Message_screen/Model/UserPersonalInfoModel.dart';
import '../Screen/Message_screen/Model/messagescreen_model.dart';
import '../Screen/NotiFicationPage/Model/Notification_Model.dart';
import '../Screen/NotiFicationPage/Model/ReadNotificationModel.dart';
import '../Screen/Oredrscreen/Model/order_detail_model.dart';
import '../Screen/Oredrscreen/Model/order_screen_model.dart';
import '../Screen/Oredrscreen/Model/service_order_model.dart';
import '../Screen/Oredrscreen/Model/service_view_model.dart';
import '../Screen/Parcel/Model/parcel_model.dart';
import '../Screen/Product Detail Page/model/all_review_model.dart';
import '../Screen/Product Detail Page/model/product_model.dart';

import '../Screen/Service Detail Page/Model/ServiceDetailsModel.dart';
import '../Screen/UpcomingRequest/Model/OnGoing_Freind_Request_Model.dart';
import '../Screen/UpcomingRequest/Model/my_request_model.dart';
import '../Screen/Visitor/Model/latest_visitor_modal/latest_visitor_modal.dart';
import '../Screen/open_ai_chatbot/modal/chat_bot_data_modal.dart';
import '../Screen/open_ai_chatbot/modal/send_data_model.dart';

// const String baseUrl = "https://wave.londontechequity.ai/api";
const String baseUrl = "https://portal.wavee.ai/api";

class AppConstants {
  static const String manrope = "Manrope";
}

LoginModel? loginModel;
Forgotpasswordmodel? forgotpasswordmodel;
DeleteAccountModel? deleteAccountModel;
ParcelViewModal? parcelViewModal;
BusinessProfileModel? businessprofileModel;
BusnessViewModal? busnessviewmodal;
ProfileModel? profileModel;
ParcelShowCountModel? parcelShowCountModel;
VisitorShowCountModel? visitorShowCountModel;
BussinessLikeModel? bussinesslikemodel;
// Hiren Api
LatestVisitorModal? latestVisitorModal;
ChatShowCountModal? chatShowCountModal;
MessageBoardModal? messageBoardModal;
ChatModel? chatModel;
MessageModel? messageModel;
BusnessSearchModal? busnesssearchModal;
GetLikeModal? getlikeModal;
GetVisitedModal? getvisitedModal;
SendMessageModel? sendMessageModel;
RequestModal? requestmodal;
EventlistModel? eventlistModel;
NotificationModell? notificationmodel;
NotificationReadModel? notificationreadModel;
EventlistModel? event_list_Model;
SendeventModel? sendeventModel;
CategoriesModel? categoriesModel;
ViewCategoriesModel? viewcategoriesmodel;
PostLikeModel? postlikemodel;
DwellTimeModel? dwelltimemodel;
PostAsViewedModel? postasviewedmodel;
OfferPromoAsViewedModel? offerpromoAsviewedmodel;
ChatUserListModel? chatuserlistmodel;
GetGroupListModel? getgrouplistmodel;
CreateGroupModel? creategroupmodel;
GroupProfileModel? groupprofileModel;
RemoveGroupMemberModel? removegroupMemberModel;
AddGroupMemberModel? addgroupMemberModel;
DeleteGroupModel? deletegroupModel;
RemoveFriendModel? removefriendModel;
UserPersonalInfoModel? userpersonalInfoModel;

// Response models
SendMsgModel? sendmsgModel;
GetMsgModel? getmsgModel;
CreateFriendModel? createfriendModel;
GetFriendListModel? getfriendListModel;
//HIren
ChatbotDataModal? chatbotDataModal;
SendChatModal? sendChatModal;
AmenitiesModel? amenitiesModel;
AmenitiesModel? aneminitiesDataModel;
AllAmenitiesModel? allAmenitiesModel;
RejectBookingModel? rejectBookingModel;
BookAmenitiesStatusModel? bookAmenitiesStatusModel;
MaintenanceModel? maintenanceModel;
EventBookingModal? eventBookingModal;
GetPostCommentsModel? getpostCommentsModel;
MessageboardpostLikeModel? messageboardpostlikeModel;
SendPostCommentsModel? sendpostCommentsModel;
MaintenanceDetailModel? maintenanceDetailModel;
EventDetailModel? eventDetailModel;
ProductViewModel? productViewModel;
ShowAllReviewModel? showAllReviewModel;
CartDetailsModel? cartDetailsModel;
CartDetailsModel? checkoutTotal;
MyOrderModel? myOrderModel;
OrderDetailModel? orderDetailModel;
PlaceOrderModel? placeOrderModel;
StroyModel? stroymodel;
GetRequestModel? getrequestModel;
MyRequestModel? myRequestModel;
OnGoingFreindRequestModel? onGoingFreindRequestModel;
MyGroupRequestModel? myGroupRequestModel;
ResidentAppUserprofileModel? residentappuserprofileModel;
ServiceDetailsModel? servicedetailsmodel;
ServiceOrderDetail? serviceOrderDetail;
ServiceViewModel? serviceViewModel;
ServiceBookingModel? serviceBookingModel;
//Ram Api
Localpost_model? localpost_model;
Localpost_comments_Model? localpost_comments_Model;
Add_Post_Model? add_Post_Model;
