name: Build Android Release

on:
  push:
    tags:
      - 'v*'
#      - 'v*-android'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.2'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # Decode keystore using your secret name
      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/waveeai.jks

      # Build the signed App Bundle
      # The env names here must match what we put in build.gradle.kts
      - name: Build App Bundle
        run: flutter build appbundle --release
        env:
          APP_STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          APP_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          APP_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # Automatic upload to Google Play Console
      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
          packageName: com.wavee.community
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
          status: completed

      # Keep a copy of the build in GitHub
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release-bundle
          path: build/app/outputs/bundle/release/app-release.aab